service: ${self:custom.service.name}

provider:
    name: aws
    runtime: nodejs12.x
    region: us-east-1
    profile: alex
    stage: dev

plugins:
    - serverless-s3-sync
    - serverless-webpack
    - serverless-create-global-dynamodb-table

package:
    individually: true

custom:
    service:
        name: myserverlessprojectuploadbucketalex
    tableName: player-points
    s3Sync:
        - bucketName: myserverlessprojectuploadbucketalex-123123
          localDir: UploadData
    globalTables:
        regions:
            - us-east-1
            - us-west-2
        createStack: false
    tag: player

functions:
    getUser:
        handler: lambdas/getUser.handler
        events:
            - http:
                  path: get-user/{ID}
                  method: GET
                  cors: true

resources:
    Resources:
        DemoBucketUpload:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: myserverlessprojectuploadbucketalex-123123
        MyDynamoDbTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.tableName}
                AttributeDefinitions:
                    - AttributeName: ID
                      AttributeType: S
                KeySchema:
                    - AttributeName: ID
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST
                StreamSpecification:
                    StreamViewType: NEW_AND_OLD_IMAGES
        coronavirus:
            Type: "AWS::DynamoDB::Table"
            Properties:
                TableName: ${self:custom.service.name}-${self:provider.stage}-coronavirus-country
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: country
                      AttributeType: S
                    - AttributeName: continent
                      AttributeType: S
                KeySchema:
                    - AttributeName: country
                      KeyType: HASH
                    - AttributeName: continent
                      KeyType: RANGE
                GlobalSecondaryIndexes:
                    - IndexName: countryIndex
                      KeySchema:
                          - AttributeName: country
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL
                    - IndexName: continentIndex
                      KeySchema:
                          - AttributeName: continent
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL
                StreamSpecification:
                    StreamViewType: NEW_AND_OLD_IMAGES